version: '3.7'

services:
  web:
    build: ./services
    command: gunicorn --bind 0.0.0.0:5000 flask_starter:app
    volumes:
      - ./services/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - "5432:5432"

volumes:
  postgres_data: